services:
  - type: web
    name: mpsif-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
